// テスト用に例外を投げる
throw new Error('test-error');
